name: production

on:
  push:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      action:
        description: 'Which action to perform'
        required: false
        default: 'Input "deploy" to deploy'

jobs:
  test:
    if: github.event.inputs.action != 'deploy'
    runs-on: ubuntu-latest
    steps:
      - run: echo "test"

  build:
    if: github.event.inputs.action != 'deploy'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - run: echo "build"

  deploy:
    if: github.event.inputs.action == 'deploy'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "deploy"